package com.gfl2.cmt.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;

@Entity
@Table(name = "TB_C_USER_ZUZAK_HISTORY")
@Data
public class CUserZuzakHistory {
	
	@Id
	@Column(name = "ID", nullable = false, insertable = false, options = "GENERATED BY DEFAULT AS IDENTITY")
	int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UID", nullable = false, insertable = true)
	CUser cUser;
	
	@Column(name = "REG_DT", nullable = false, insertable = true , options = "DEFAULT CURRENT_TIMESTAMP")
	LocalDateTime reg_dt;
	
	@Column(columnDefinition = "BOOLEAN")
	boolean isZuzak;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@Column(name = "GUN_SMOKE_ID", nullable = true, insertable = true)
	GunSmoke gunSmoke;

}
