package com.gfl2.cmt.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.FetchType;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;

public class CUserGunSmokeHistory {
	
	@Column(name = "id", nullable = false, unique = true, insertable = false, options = "GENERATED BY DEFAULT AS IDENTITY")
	int id;
	
	@Column(name = "day", nullable = false, insertable = true)
	int day;
	
	@Column(name = "score", nullable = false, insertable = true)
	int score;
	
	@Column(name = "attempt", nullable = false, insertable = true)
	int attempt;
	
	@OneToOne(fetch = FetchType.LAZY)
	CUser cUser;
	
	@OneToOne(fetch = FetchType.LAZY)
	GunSmoke gunSmoke;
	
	@Column(name = "reg_dt", nullable = false, insertable = true , options = "DEFAULT CURRENT_TIMESTAMP")
	LocalDateTime reg_dt;
	
	@Column(name="t_dolls", nullable = true, insertable = true)
	String tdolls;
	
	

}
