package com.gfl2.cmt.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.ManyToOne;
import lombok.Data;

@Data
@Entity
public class CUserContibuteHistory {
	
	@Column(name = "id", nullable = false, unique = true, insertable = false, options = "GENERATED BY DEFAULT AS IDENTITY")
	int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	CUser user;
	
	@Column(name = "reg_dt", nullable = false, insertable = true , options = "DEFAULT CURRENT_TIMESTAMP")
	LocalDateTime regDate;
	
	@Column(name = "contribute_value", nullable = false, insertable = true)
	int contibuteValue;
	

}
