package com.gfl2.cmt.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.Data;

@Entity
@Data
public class GunSmoke {
	
	@Column(name = "id", nullable = false, unique = true, insertable = false, options = "GENERATED BY DEFAULT AS IDENTITY")
	@Id
	int id;
	
	@Column(name = "start_dt", nullable = false, insertable = true)
	LocalDateTime start_dt;
	
	@Column(name = "end_dt", nullable = false, insertable = true)
	LocalDateTime end_dt;
	
	@Column(name = "kill_score", nullable = false, insertable = true)
	int kill_score;
	
	

}
