package com.gfl2.cmt.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Column;

public class GunSmoke {
	
	@Column(name = "id", nullable = false, unique = true, insertable = false, options = "GENERATED BY DEFAULT AS IDENTITY")
	int id;
	
	@Column(name = "name", nullable = false, insertable = true)
	LocalDateTime start_dt;
	
	@Column(name = "name", nullable = false, insertable = true)
	LocalDateTime end_dt;
	
	@Column(name = "kill_score", nullable = false, insertable = true)
	int kill_score;
	
	

}
